### PR TITLE
Add a basic Flutter CI-pipeline

### PR DESCRIPTION
**Pull request by spydon**
This adds a GitHub pipeline that checks formatting, analyzer errors and tests.

### CODE REVIEW

**Comment by spydon** [comment]
I don't think it can run since `pub get` is failing towards the `artifactory_proxy_url`

**Comment by spydon** [comment]
@teodor-appd I can't run `pub get` locally either without swapping to `pub.dev`, so I guess that the proxy url only is accessible from within your VPN or such?

**Comment by teodor-appd** [comment]
@spydon I was hoping it would fall back to pub.dev, but it seems not. The proxy mechanism is really primitive for Flutter. I'll need to change that, but not sure when. Any workarounds for you for now?

**Comment by spydon** [comment]
> @spydon I was hoping it would fall back to pub.dev, but it seems not. The proxy mechanism is really primitive for Flutter. I'll need to change that, but not sure when. Any workarounds for you for now?

The only workaround that I can think of is just going directly towards pub.dev instead of to your artifactory.

**Comment by teodor-appd** [comment]
@spydon I'll try to find a workaround for a proxy to fall back. Give me one day. If not, I need to remove the proxy logic.

**Comment by spydon** [comment]
No rush, maybe the `PUB_HOSTED_URL` environment variable could help?
Not sure how you're using your own hosted pub internally, because if it is not reachable from outside of your network the packages can't be published with the proxy active right? And since you use dependency ranges, it could still be fetched from pub.dev when doing version resolution with other dependencies right (for users of this package)?

**Comment by teodor-appd** [comment]
@spydon PUB_HOSTED_URL would work, but where can I set it such that all users of this repo have it automatically set? We would need a pre-build step in the project, and I need to learn about Flutter providing such.

However, your other points make good sense. It might be that the package would not even work on customer projects with these proxy changes, PUB_HOSTER_URL or not. I will remove them as they don't work as intended, e.g. sub-dependencies are still dragged from pub.dev (or even your dependency range example)

**Pull request merged**
